name: 'Continuous Integration'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  OPENAI_API_TYPE: ${{ vars.OPENAI_API_TYPE }}
  OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
  OPENAI_ENGINE: ${{ vars.OPENAI_ENGINE }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: examples/**
        separator: ','
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done        
    - if: steps.changed-files.outputs.any_changed == 'true'
      uses: ./
      with:
        topic-files: ${{ steps.changed-files.outputs.all_changed_files }}
        output-dir: 'docs'
        remove-prefix: 'examples/'
    - uses: stefanzweifel/git-auto-commit-action@v4
